// <auto-generated />
using System;
using System.Collections.Generic;
using EducationPath.LearningPaths.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationPath.LearningPaths.Infrastructure.Migrations
{
    [DbContext(typeof(LearningPathsWriteDbContext))]
    partial class LearningPathsWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning_paths")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Links")
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.ComplexProperty<Dictionary<string, object>>("Content", "EducationPath.LearningPaths.Domain.Entities.Lesson.Content#LessonContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("content");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "EducationPath.LearningPaths.Domain.Entities.Lesson.Title#LessonTitle", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("RoadmapId")
                        .HasDatabaseName("ix_lessons_roadmap_id");

                    b.ToTable("lessons", "learning_paths");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.LessonDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromLessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_lesson_id");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_id");

                    b.Property<Guid>("ToLessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_lesson_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_dependencies");

                    b.HasIndex("FromLessonId")
                        .HasDatabaseName("ix_lesson_dependencies_from_lesson_id");

                    b.HasIndex("RoadmapId")
                        .HasDatabaseName("ix_lesson_dependencies_roadmap_id");

                    b.HasIndex("ToLessonId")
                        .HasDatabaseName("ix_lesson_dependencies_to_lesson_id");

                    b.ToTable("lesson_dependencies", "learning_paths");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "EducationPath.LearningPaths.Domain.Entities.Roadmap.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "EducationPath.LearningPaths.Domain.Entities.Roadmap.Title#RoadmapTitle", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pk_roadmaps");

                    b.ToTable("roadmaps", "learning_paths");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("EducationPath.LearningPaths.Domain.Entities.Roadmap", null)
                        .WithMany("Lessons")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_roadmaps_roadmap_id");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.LessonDependency", b =>
                {
                    b.HasOne("EducationPath.LearningPaths.Domain.Entities.Lesson", "FromLesson")
                        .WithMany("OutgoingDependencies")
                        .HasForeignKey("FromLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_dependencies_lessons_from_lesson_id");

                    b.HasOne("EducationPath.LearningPaths.Domain.Entities.Roadmap", null)
                        .WithMany("LessonsDependencies")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_dependencies_roadmaps_roadmap_id");

                    b.HasOne("EducationPath.LearningPaths.Domain.Entities.Lesson", "ToLesson")
                        .WithMany("IncomingDependencies")
                        .HasForeignKey("ToLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_dependencies_lessons_to_lesson_id");

                    b.Navigation("FromLesson");

                    b.Navigation("ToLesson");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("IncomingDependencies");

                    b.Navigation("OutgoingDependencies");
                });

            modelBuilder.Entity("EducationPath.LearningPaths.Domain.Entities.Roadmap", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("LessonsDependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
