// <auto-generated />
using System;
using System.Collections.Generic;
using EducationPath.Skills.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationPath.Skills.Infrastructure.Migrations
{
    [DbContext(typeof(SkillsWriteDbContext))]
    [Migration("20251104105539_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("skills")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationPath.Skills.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "EducationPath.Skills.Domain.Entities.Skill.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EducationPath.Skills.Domain.Entities.Skill.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_skills_parent_id");

                    b.ToTable("skills", "skills");
                });

            modelBuilder.Entity("EducationPath.Skills.Domain.Entities.Skill", b =>
                {
                    b.HasOne("EducationPath.Skills.Domain.Entities.Skill", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_skills_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EducationPath.Skills.Domain.Entities.Skill", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
